### ISSUE TITLE
NoMethodError: undefined method `collections' for nil:NilClass

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#2655]
Bug was introduced in https://github.com/ualbertalib/jupiter/commit/c1648f28a941b59b0dc9e9b86d073da3d83e0e42

In the js format section we missed a change from `@community` to `community`

You can trigger the error by clicking any of the Collections drop down on the Communities page
![image](https://user-images.githubusercontent.com/1220762/145244245-050fd26d-7a9e-4f66-ae04-4abbb8d4d322.png)

View details in Rollbar: [https://rollbar.com/ualbertalib/jupiter/items/1327/](https://rollbar.com/ualbertalib/jupiter/items/1327/)

```

NoMethodError: undefined method `collections' for nil:NilClass
  File "/var/www/sites/jupiter/app/controllers/communities_controller.rb", line 37, in block (2 levels) in show
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_controller/metal/mime_responds.rb", line 214, in respond_to
  File "/var/www/sites/jupiter/app/controllers/communities_controller.rb", line 30, in show
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_controller/metal/basic_implicit_render.rb", line 6, in send_action
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/abstract_controller/base.rb", line 195, in process_action
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_controller/metal/rendering.rb", line 30, in process_action
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/abstract_controller/callbacks.rb", line 42, in block in process_action
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb", line 135, in run_callbacks
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/abstract_controller/callbacks.rb", line 41, in process_action
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_controller/metal/rescue.rb", line 22, in process_action
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_controller/metal/instrumentation.rb", line 33, in block in process_action
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activesupport-6.0.4.1/lib/active_support/notifications.rb", line 180, in block in instrument
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activesupport-6.0.4.1/lib/active_support/notifications/instrumenter.rb", line 24, in instrument
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activesupport-6.0.4.1/lib/active_support/notifications.rb", line 180, in instrument
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_controller/metal/instrumentation.rb", line 32, in process_action
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_controller/metal/params_wrapper.rb", line 245, in process_action
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activerecord-6.0.4.1/lib/active_record/railties/controller_runtime.rb", line 27, in process_action
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/abstract_controller/base.rb", line 136, in process
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionview-6.0.4.1/lib/action_view/rendering.rb", line 39, in process
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_controller/metal.rb", line 190, in dispatch
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_controller/metal.rb", line 254, in dispatch
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_dispatch/routing/route_set.rb", line 50, in dispatch
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_dispatch/routing/route_set.rb", line 33, in serve
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_dispatch/journey/router.rb", line 49, in block in serve
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_dispatch/journey/router.rb", line 32, in each
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_dispatch/journey/router.rb", line 32, in serve
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_dispatch/routing/route_set.rb", line 834, in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/skylight-core-4.3.2/lib/skylight/core/probes/action_dispatch/routing/route_set.rb", line 14, in block in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/skylight-core-4.3.2/lib/skylight/core/fanout.rb", line 25, in instrument
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/skylight-core-4.3.2/lib/skylight/core/probes/action_dispatch/routing/route_set.rb", line 13, in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/omniauth-2.0.4/lib/omniauth/strategy.rb", line 470, in call_app!
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/omniauth-saml-2.0.0/lib/omniauth/strategies/saml.rb", line 86, in other_phase
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/omniauth-2.0.4/lib/omniauth/strategy.rb", line 195, in call!
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/omniauth-2.0.4/lib/omniauth/strategy.rb", line 169, in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/omniauth-2.0.4/lib/omniauth/builder.rb", line 45, in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_dispatch/middleware/stack.rb", line 61, in block in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activesupport-6.0.4.1/lib/active_support/notifications.rb", line 180, in block in instrument
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activesupport-6.0.4.1/lib/active_support/notifications/instrumenter.rb", line 24, in instrument
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activesupport-6.0.4.1/lib/active_support/notifications.rb", line 180, in instrument
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_dispatch/middleware/stack.rb", line 60, in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/flipper-0.22.2/lib/flipper/middleware/memoizer.rb", line 77, in memoized_call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/flipper-0.22.2/lib/flipper/middleware/memoizer.rb", line 42, in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_dispatch/middleware/stack.rb", line 61, in block in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activesupport-6.0.4.1/lib/active_support/notifications.rb", line 180, in block in instrument
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activesupport-6.0.4.1/lib/active_support/notifications/instrumenter.rb", line 24, in instrument
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activesupport-6.0.4.1/lib/active_support/notifications.rb", line 180, in instrument
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_dispatch/middleware/stack.rb", line 60, in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb", line 15, in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/actionpack-6.0.4.1/lib/action_dispatch/middleware/stack.rb", line 61, in block in call
  File "/var/www/sites/jupiter/vendor/ruby/2.6.0/gems/activesupport-6.0.4.1/lib/active_support/notifications.rb", line 180, in block in in

**Comment by pgwillia** [comment]
In production! jupiter-2.3.2
